### PR TITLE
Adding symlinks to schema. Resolves zeit/serve#519

### PR DESCRIPTION
**Pull request by joeldenning**
See https://github.com/zeit/serve/issues/519

### CODE REVIEW

**Comment by joeldenning** [comment]
any update on this?

**Comment by joeldenning** [comment]
any update?

**Comment by joeldenning** [comment]
any update?

**Comment by dariusbakunas** [comment]
For those looking for a temporary fix, I had some success with using `patch` utility to apply this patch after `serve` is installed:

```
diff --git a/node_modules/@zeit/schemas/deployment/config-static.js b/node_modules/@zeit/schemas/deployment/config-static.js
index 55cff95..7e713c5 100644
--- a/node_modules/@zeit/schemas/deployment/config-static.js
+++ b/node_modules/@zeit/schemas/deployment/config-static.js
@@ -73,6 +73,9 @@ module.exports = {
 		},
 		'renderSingle': {
 			type: 'boolean'
+		},
+		'symlinks': {
+			type: 'boolean'
 		}
 	},
 	additionalProperties: false
```

save this file as `@zeit+schemas+2.6.0.patch` and then patch command like so:

```
% patch -p1 -d /usr/local/share/.config/yarn/global < @zeit+schemas+2.6.0.patch
```

**Note**: I am using `yarn` to install `serve` globally, so your `node_modules` location might be different

Or there is also https://www.npmjs.com/package/patch-package that could apply the same patch in `postinstall` step (that is if you don't install `serve` globally)

**Comment by joeldenning** [comment]
I don't represent vercel but do not think it's helpful to express anger or sarcasm over this. This is an open source project and the maintainers of it owe us nothing.

**Comment by Dinhero21** [comment]
4 years later and it still hasn't been merged?

**Comment by Johennes** [comment]
@AndyBitz maybe you could help with this?

**Review by AndyBitz — APPROVED** [review]
Thank you, I'll tend to it.

**Comment by Johennes** [comment]
Thank you! 🙂

**Pull request merged**
